////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2015 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 16.20Release
// Tag = development-akw-16.20.00-0
////////////////////////////////////////////////////////////////////////////////


#if !defined(FIT_VIDEO_MESG_HPP)
#define FIT_VIDEO_MESG_HPP

#include "fit_mesg.hpp"

namespace fit
{

class VideoMesg : public Mesg
{
   public:
      VideoMesg(void) : Mesg(Profile::MESG_VIDEO)
      {
      }

      VideoMesg(const Mesg &mesg) : Mesg(mesg)
      {
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns url field
      ///////////////////////////////////////////////////////////////////////
      FIT_WSTRING GetUrl(void) const
      {
         return GetFieldSTRINGValue(0, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set url field
      ///////////////////////////////////////////////////////////////////////
      void SetUrl(FIT_WSTRING url)
      {
         SetFieldSTRINGValue(0, url, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns hosting_provider field
      ///////////////////////////////////////////////////////////////////////
      FIT_WSTRING GetHostingProvider(void) const
      {
         return GetFieldSTRINGValue(1, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set hosting_provider field
      ///////////////////////////////////////////////////////////////////////
      void SetHostingProvider(FIT_WSTRING hostingProvider)
      {
         SetFieldSTRINGValue(1, hostingProvider, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns duration field
      // Units: ms
      // Comment: Playback time of video
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT32 GetDuration(void) const
      {
         return GetFieldUINT32Value(2, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set duration field
      // Units: ms
      // Comment: Playback time of video
      ///////////////////////////////////////////////////////////////////////
      void SetDuration(FIT_UINT32 duration)
      {
         SetFieldUINT32Value(2, duration, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

};

} // namespace fit

#endif // !defined(FIT_VIDEO_MESG_HPP)
