////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2015 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 16.20Release
// Tag = development-akw-16.20.00-0
////////////////////////////////////////////////////////////////////////////////


#if !defined(FIT_THREE_D_SENSOR_CALIBRATION_MESG_HPP)
#define FIT_THREE_D_SENSOR_CALIBRATION_MESG_HPP

#include "fit_mesg.hpp"

namespace fit
{

class ThreeDSensorCalibrationMesg : public Mesg
{
   public:
      ThreeDSensorCalibrationMesg(void) : Mesg(Profile::MESG_THREE_D_SENSOR_CALIBRATION)
      {
      }

      ThreeDSensorCalibrationMesg(const Mesg &mesg) : Mesg(mesg)
      {
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns timestamp field
      // Units: s
      // Comment: Whole second part of the timestamp
      ///////////////////////////////////////////////////////////////////////
      FIT_DATE_TIME GetTimestamp(void) const
      {
         return GetFieldUINT32Value(253, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set timestamp field
      // Units: s
      // Comment: Whole second part of the timestamp
      ///////////////////////////////////////////////////////////////////////
      void SetTimestamp(FIT_DATE_TIME timestamp)
      {
         SetFieldUINT32Value(253, timestamp, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns sensor_type field
      // Comment: Indicates which sensor the calibration is for
      ///////////////////////////////////////////////////////////////////////
      FIT_SENSOR_TYPE GetSensorType(void) const
      {
         return GetFieldENUMValue(0, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set sensor_type field
      // Comment: Indicates which sensor the calibration is for
      ///////////////////////////////////////////////////////////////////////
      void SetSensorType(FIT_SENSOR_TYPE sensorType)
      {
         SetFieldENUMValue(0, sensorType, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns calibration_factor field
      // Comment: Calibration factor used to convert from raw ADC value to degrees, g,  etc.
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT32 GetCalibrationFactor(void) const
      {
         return GetFieldUINT32Value(1, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set calibration_factor field
      // Comment: Calibration factor used to convert from raw ADC value to degrees, g,  etc.
      ///////////////////////////////////////////////////////////////////////
      void SetCalibrationFactor(FIT_UINT32 calibrationFactor)
      {
         SetFieldUINT32Value(1, calibrationFactor, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns accel_cal_factor field
      // Units: g
      // Comment: Accelerometer calibration factor
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT32 GetAccelCalFactor(void) const
      {
         return GetFieldUINT32Value(1, 0, (FIT_UINT16) Profile::THREE_D_SENSOR_CALIBRATION_MESG_CALIBRATION_FACTOR_FIELD_ACCEL_CAL_FACTOR);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set accel_cal_factor field
      // Units: g
      // Comment: Accelerometer calibration factor
      ///////////////////////////////////////////////////////////////////////
      void SetAccelCalFactor(FIT_UINT32 accelCalFactor)
      {
         SetFieldUINT32Value(1, accelCalFactor, 0, (FIT_UINT16) Profile::THREE_D_SENSOR_CALIBRATION_MESG_CALIBRATION_FACTOR_FIELD_ACCEL_CAL_FACTOR);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns gyro_cal_factor field
      // Units: deg/s
      // Comment: Gyro calibration factor
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT32 GetGyroCalFactor(void) const
      {
         return GetFieldUINT32Value(1, 0, (FIT_UINT16) Profile::THREE_D_SENSOR_CALIBRATION_MESG_CALIBRATION_FACTOR_FIELD_GYRO_CAL_FACTOR);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set gyro_cal_factor field
      // Units: deg/s
      // Comment: Gyro calibration factor
      ///////////////////////////////////////////////////////////////////////
      void SetGyroCalFactor(FIT_UINT32 gyroCalFactor)
      {
         SetFieldUINT32Value(1, gyroCalFactor, 0, (FIT_UINT16) Profile::THREE_D_SENSOR_CALIBRATION_MESG_CALIBRATION_FACTOR_FIELD_GYRO_CAL_FACTOR);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns calibration_divisor field
      // Units: counts
      // Comment: Calibration factor divisor
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT32 GetCalibrationDivisor(void) const
      {
         return GetFieldUINT32Value(2, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set calibration_divisor field
      // Units: counts
      // Comment: Calibration factor divisor
      ///////////////////////////////////////////////////////////////////////
      void SetCalibrationDivisor(FIT_UINT32 calibrationDivisor)
      {
         SetFieldUINT32Value(2, calibrationDivisor, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns level_shift field
      // Comment: Level shift value used to shift the ADC value back into range
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT32 GetLevelShift(void) const
      {
         return GetFieldUINT32Value(3, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set level_shift field
      // Comment: Level shift value used to shift the ADC value back into range
      ///////////////////////////////////////////////////////////////////////
      void SetLevelShift(FIT_UINT32 levelShift)
      {
         SetFieldUINT32Value(3, levelShift, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns number of offset_cal
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT8 GetNumOffsetCal(void) const
      {
         return GetFieldNumValues(4, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns offset_cal field
      // Comment: Internal calibration factors, one for each: xy, yx, zx
      ///////////////////////////////////////////////////////////////////////
      FIT_SINT32 GetOffsetCal(FIT_UINT8 index) const
      {
         return GetFieldSINT32Value(4, index, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set offset_cal field
      // Comment: Internal calibration factors, one for each: xy, yx, zx
      ///////////////////////////////////////////////////////////////////////
      void SetOffsetCal(FIT_UINT8 index, FIT_SINT32 offsetCal)
      {
         SetFieldSINT32Value(4, offsetCal, index, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns number of orientation_matrix
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT8 GetNumOrientationMatrix(void) const
      {
         return GetFieldNumValues(5, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns orientation_matrix field
      // Comment: 3 x 3 rotation matrix (row major)
      ///////////////////////////////////////////////////////////////////////
      FIT_FLOAT32 GetOrientationMatrix(FIT_UINT8 index) const
      {
         return GetFieldFLOAT32Value(5, index, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set orientation_matrix field
      // Comment: 3 x 3 rotation matrix (row major)
      ///////////////////////////////////////////////////////////////////////
      void SetOrientationMatrix(FIT_UINT8 index, FIT_FLOAT32 orientationMatrix)
      {
         SetFieldFLOAT32Value(5, orientationMatrix, index, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

};

} // namespace fit

#endif // !defined(FIT_THREE_D_SENSOR_CALIBRATION_MESG_HPP)
