////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2015 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 16.20Release
// Tag = development-akw-16.20.00-0
////////////////////////////////////////////////////////////////////////////////


#if !defined(FIT_SEGMENT_LEADERBOARD_ENTRY_MESG_HPP)
#define FIT_SEGMENT_LEADERBOARD_ENTRY_MESG_HPP

#include "fit_mesg.hpp"

namespace fit
{

class SegmentLeaderboardEntryMesg : public Mesg
{
   public:
      SegmentLeaderboardEntryMesg(void) : Mesg(Profile::MESG_SEGMENT_LEADERBOARD_ENTRY)
      {
      }

      SegmentLeaderboardEntryMesg(const Mesg &mesg) : Mesg(mesg)
      {
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns message_index field
      ///////////////////////////////////////////////////////////////////////
      FIT_MESSAGE_INDEX GetMessageIndex(void) const
      {
         return GetFieldUINT16Value(254, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set message_index field
      ///////////////////////////////////////////////////////////////////////
      void SetMessageIndex(FIT_MESSAGE_INDEX messageIndex)
      {
         SetFieldUINT16Value(254, messageIndex, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns name field
      // Comment: Friendly name assigned to leader
      ///////////////////////////////////////////////////////////////////////
      FIT_WSTRING GetName(void) const
      {
         return GetFieldSTRINGValue(0, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set name field
      // Comment: Friendly name assigned to leader
      ///////////////////////////////////////////////////////////////////////
      void SetName(FIT_WSTRING name)
      {
         SetFieldSTRINGValue(0, name, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns type field
      // Comment: Leader classification
      ///////////////////////////////////////////////////////////////////////
      FIT_SEGMENT_LEADERBOARD_TYPE GetType(void) const
      {
         return GetFieldENUMValue(1, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set type field
      // Comment: Leader classification
      ///////////////////////////////////////////////////////////////////////
      void SetType(FIT_SEGMENT_LEADERBOARD_TYPE type)
      {
         SetFieldENUMValue(1, type, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns group_primary_key field
      // Comment: Primary user ID of this leader
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT32 GetGroupPrimaryKey(void) const
      {
         return GetFieldUINT32Value(2, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set group_primary_key field
      // Comment: Primary user ID of this leader
      ///////////////////////////////////////////////////////////////////////
      void SetGroupPrimaryKey(FIT_UINT32 groupPrimaryKey)
      {
         SetFieldUINT32Value(2, groupPrimaryKey, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns activity_id field
      // Comment: ID of the activity associated with this leader time
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT32 GetActivityId(void) const
      {
         return GetFieldUINT32Value(3, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set activity_id field
      // Comment: ID of the activity associated with this leader time
      ///////////////////////////////////////////////////////////////////////
      void SetActivityId(FIT_UINT32 activityId)
      {
         SetFieldUINT32Value(3, activityId, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns segment_time field
      // Units: s
      // Comment: Segment Time (includes pauses)
      ///////////////////////////////////////////////////////////////////////
      FIT_FLOAT32 GetSegmentTime(void) const
      {
         return GetFieldFLOAT32Value(4, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set segment_time field
      // Units: s
      // Comment: Segment Time (includes pauses)
      ///////////////////////////////////////////////////////////////////////
      void SetSegmentTime(FIT_FLOAT32 segmentTime)
      {
         SetFieldFLOAT32Value(4, segmentTime, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns activity_id_string field
      // Comment: String version of the activity_id. 21 characters long, express in decimal
      ///////////////////////////////////////////////////////////////////////
      FIT_WSTRING GetActivityIdString(void) const
      {
         return GetFieldSTRINGValue(5, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set activity_id_string field
      // Comment: String version of the activity_id. 21 characters long, express in decimal
      ///////////////////////////////////////////////////////////////////////
      void SetActivityIdString(FIT_WSTRING activityIdString)
      {
         SetFieldSTRINGValue(5, activityIdString, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

};

} // namespace fit

#endif // !defined(FIT_SEGMENT_LEADERBOARD_ENTRY_MESG_HPP)
