////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2015 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 16.20Release
// Tag = development-akw-16.20.00-0
////////////////////////////////////////////////////////////////////////////////


#if !defined(FIT_VIDEO_CLIP_MESG_HPP)
#define FIT_VIDEO_CLIP_MESG_HPP

#include "fit_mesg.hpp"

namespace fit
{

class VideoClipMesg : public Mesg
{
   public:
      VideoClipMesg(void) : Mesg(Profile::MESG_VIDEO_CLIP)
      {
      }

      VideoClipMesg(const Mesg &mesg) : Mesg(mesg)
      {
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns clip_number field
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT16 GetClipNumber(void) const
      {
         return GetFieldUINT16Value(0, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set clip_number field
      ///////////////////////////////////////////////////////////////////////
      void SetClipNumber(FIT_UINT16 clipNumber)
      {
         SetFieldUINT16Value(0, clipNumber, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns start_timestamp field
      ///////////////////////////////////////////////////////////////////////
      FIT_DATE_TIME GetStartTimestamp(void) const
      {
         return GetFieldUINT32Value(1, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set start_timestamp field
      ///////////////////////////////////////////////////////////////////////
      void SetStartTimestamp(FIT_DATE_TIME startTimestamp)
      {
         SetFieldUINT32Value(1, startTimestamp, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns start_timestamp_ms field
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT16 GetStartTimestampMs(void) const
      {
         return GetFieldUINT16Value(2, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set start_timestamp_ms field
      ///////////////////////////////////////////////////////////////////////
      void SetStartTimestampMs(FIT_UINT16 startTimestampMs)
      {
         SetFieldUINT16Value(2, startTimestampMs, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns end_timestamp field
      ///////////////////////////////////////////////////////////////////////
      FIT_DATE_TIME GetEndTimestamp(void) const
      {
         return GetFieldUINT32Value(3, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set end_timestamp field
      ///////////////////////////////////////////////////////////////////////
      void SetEndTimestamp(FIT_DATE_TIME endTimestamp)
      {
         SetFieldUINT32Value(3, endTimestamp, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns end_timestamp_ms field
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT16 GetEndTimestampMs(void) const
      {
         return GetFieldUINT16Value(4, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set end_timestamp_ms field
      ///////////////////////////////////////////////////////////////////////
      void SetEndTimestampMs(FIT_UINT16 endTimestampMs)
      {
         SetFieldUINT16Value(4, endTimestampMs, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns clip_start field
      // Units: ms
      // Comment: Start of clip in video time
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT32 GetClipStart(void) const
      {
         return GetFieldUINT32Value(6, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set clip_start field
      // Units: ms
      // Comment: Start of clip in video time
      ///////////////////////////////////////////////////////////////////////
      void SetClipStart(FIT_UINT32 clipStart)
      {
         SetFieldUINT32Value(6, clipStart, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns clip_end field
      // Units: ms
      // Comment: End of clip in video time
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT32 GetClipEnd(void) const
      {
         return GetFieldUINT32Value(7, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set clip_end field
      // Units: ms
      // Comment: End of clip in video time
      ///////////////////////////////////////////////////////////////////////
      void SetClipEnd(FIT_UINT32 clipEnd)
      {
         SetFieldUINT32Value(7, clipEnd, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

};

} // namespace fit

#endif // !defined(FIT_VIDEO_CLIP_MESG_HPP)
