////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2015 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 16.20Release
// Tag = development-akw-16.20.00-0
////////////////////////////////////////////////////////////////////////////////


#if !defined(FIT_SEGMENT_LAP_MESG_HPP)
#define FIT_SEGMENT_LAP_MESG_HPP

#include "fit_mesg.hpp"
#include "fit_mesg_with_event.hpp"

namespace fit
{

class SegmentLapMesg : public Mesg, public MesgWithEvent
{
   public:
      SegmentLapMesg(void) : Mesg(Profile::MESG_SEGMENT_LAP)
      {
      }

      SegmentLapMesg(const Mesg &mesg) : Mesg(mesg)
      {
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns message_index field
      ///////////////////////////////////////////////////////////////////////
      FIT_MESSAGE_INDEX GetMessageIndex(void) const
      {
         return GetFieldUINT16Value(254, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set message_index field
      ///////////////////////////////////////////////////////////////////////
      void SetMessageIndex(FIT_MESSAGE_INDEX messageIndex)
      {
         SetFieldUINT16Value(254, messageIndex, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns timestamp field
      // Units: s
      // Comment: Lap end time.
      ///////////////////////////////////////////////////////////////////////
      FIT_DATE_TIME GetTimestamp(void) const
      {
         return GetFieldUINT32Value(253, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set timestamp field
      // Units: s
      // Comment: Lap end time.
      ///////////////////////////////////////////////////////////////////////
      void SetTimestamp(FIT_DATE_TIME timestamp)
      {
         SetFieldUINT32Value(253, timestamp, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns event field
      ///////////////////////////////////////////////////////////////////////
      FIT_EVENT GetEvent(void) const
      {
         return GetFieldENUMValue(0, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set event field
      ///////////////////////////////////////////////////////////////////////
      void SetEvent(FIT_EVENT event)
      {
         SetFieldENUMValue(0, event, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns event_type field
      ///////////////////////////////////////////////////////////////////////
      FIT_EVENT_TYPE GetEventType(void) const
      {
         return GetFieldENUMValue(1, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set event_type field
      ///////////////////////////////////////////////////////////////////////
      void SetEventType(FIT_EVENT_TYPE eventType)
      {
         SetFieldENUMValue(1, eventType, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns start_time field
      ///////////////////////////////////////////////////////////////////////
      FIT_DATE_TIME GetStartTime(void) const
      {
         return GetFieldUINT32Value(2, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set start_time field
      ///////////////////////////////////////////////////////////////////////
      void SetStartTime(FIT_DATE_TIME startTime)
      {
         SetFieldUINT32Value(2, startTime, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns start_position_lat field
      // Units: semicircles
      ///////////////////////////////////////////////////////////////////////
      FIT_SINT32 GetStartPositionLat(void) const
      {
         return GetFieldSINT32Value(3, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set start_position_lat field
      // Units: semicircles
      ///////////////////////////////////////////////////////////////////////
      void SetStartPositionLat(FIT_SINT32 startPositionLat)
      {
         SetFieldSINT32Value(3, startPositionLat, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns start_position_long field
      // Units: semicircles
      ///////////////////////////////////////////////////////////////////////
      FIT_SINT32 GetStartPositionLong(void) const
      {
         return GetFieldSINT32Value(4, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set start_position_long field
      // Units: semicircles
      ///////////////////////////////////////////////////////////////////////
      void SetStartPositionLong(FIT_SINT32 startPositionLong)
      {
         SetFieldSINT32Value(4, startPositionLong, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns end_position_lat field
      // Units: semicircles
      ///////////////////////////////////////////////////////////////////////
      FIT_SINT32 GetEndPositionLat(void) const
      {
         return GetFieldSINT32Value(5, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set end_position_lat field
      // Units: semicircles
      ///////////////////////////////////////////////////////////////////////
      void SetEndPositionLat(FIT_SINT32 endPositionLat)
      {
         SetFieldSINT32Value(5, endPositionLat, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns end_position_long field
      // Units: semicircles
      ///////////////////////////////////////////////////////////////////////
      FIT_SINT32 GetEndPositionLong(void) const
      {
         return GetFieldSINT32Value(6, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set end_position_long field
      // Units: semicircles
      ///////////////////////////////////////////////////////////////////////
      void SetEndPositionLong(FIT_SINT32 endPositionLong)
      {
         SetFieldSINT32Value(6, endPositionLong, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns total_elapsed_time field
      // Units: s
      // Comment: Time (includes pauses)
      ///////////////////////////////////////////////////////////////////////
      FIT_FLOAT32 GetTotalElapsedTime(void) const
      {
         return GetFieldFLOAT32Value(7, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set total_elapsed_time field
      // Units: s
      // Comment: Time (includes pauses)
      ///////////////////////////////////////////////////////////////////////
      void SetTotalElapsedTime(FIT_FLOAT32 totalElapsedTime)
      {
         SetFieldFLOAT32Value(7, totalElapsedTime, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns total_timer_time field
      // Units: s
      // Comment: Timer Time (excludes pauses)
      ///////////////////////////////////////////////////////////////////////
      FIT_FLOAT32 GetTotalTimerTime(void) const
      {
         return GetFieldFLOAT32Value(8, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set total_timer_time field
      // Units: s
      // Comment: Timer Time (excludes pauses)
      ///////////////////////////////////////////////////////////////////////
      void SetTotalTimerTime(FIT_FLOAT32 totalTimerTime)
      {
         SetFieldFLOAT32Value(8, totalTimerTime, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns total_distance field
      // Units: m
      ///////////////////////////////////////////////////////////////////////
      FIT_FLOAT32 GetTotalDistance(void) const
      {
         return GetFieldFLOAT32Value(9, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set total_distance field
      // Units: m
      ///////////////////////////////////////////////////////////////////////
      void SetTotalDistance(FIT_FLOAT32 totalDistance)
      {
         SetFieldFLOAT32Value(9, totalDistance, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns total_cycles field
      // Units: cycles
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT32 GetTotalCycles(void) const
      {
         return GetFieldUINT32Value(10, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set total_cycles field
      // Units: cycles
      ///////////////////////////////////////////////////////////////////////
      void SetTotalCycles(FIT_UINT32 totalCycles)
      {
         SetFieldUINT32Value(10, totalCycles, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns total_strokes field
      // Units: strokes
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT32 GetTotalStrokes(void) const
      {
         return GetFieldUINT32Value(10, 0, (FIT_UINT16) Profile::SEGMENT_LAP_MESG_TOTAL_CYCLES_FIELD_TOTAL_STROKES);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set total_strokes field
      // Units: strokes
      ///////////////////////////////////////////////////////////////////////
      void SetTotalStrokes(FIT_UINT32 totalStrokes)
      {
         SetFieldUINT32Value(10, totalStrokes, 0, (FIT_UINT16) Profile::SEGMENT_LAP_MESG_TOTAL_CYCLES_FIELD_TOTAL_STROKES);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns total_calories field
      // Units: kcal
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT16 GetTotalCalories(void) const
      {
         return GetFieldUINT16Value(11, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set total_calories field
      // Units: kcal
      ///////////////////////////////////////////////////////////////////////
      void SetTotalCalories(FIT_UINT16 totalCalories)
      {
         SetFieldUINT16Value(11, totalCalories, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns total_fat_calories field
      // Units: kcal
      // Comment: If New Leaf
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT16 GetTotalFatCalories(void) const
      {
         return GetFieldUINT16Value(12, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set total_fat_calories field
      // Units: kcal
      // Comment: If New Leaf
      ///////////////////////////////////////////////////////////////////////
      void SetTotalFatCalories(FIT_UINT16 totalFatCalories)
      {
         SetFieldUINT16Value(12, totalFatCalories, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns avg_speed field
      // Units: m/s
      ///////////////////////////////////////////////////////////////////////
      FIT_FLOAT32 GetAvgSpeed(void) const
      {
         return GetFieldFLOAT32Value(13, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set avg_speed field
      // Units: m/s
      ///////////////////////////////////////////////////////////////////////
      void SetAvgSpeed(FIT_FLOAT32 avgSpeed)
      {
         SetFieldFLOAT32Value(13, avgSpeed, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns max_speed field
      // Units: m/s
      ///////////////////////////////////////////////////////////////////////
      FIT_FLOAT32 GetMaxSpeed(void) const
      {
         return GetFieldFLOAT32Value(14, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set max_speed field
      // Units: m/s
      ///////////////////////////////////////////////////////////////////////
      void SetMaxSpeed(FIT_FLOAT32 maxSpeed)
      {
         SetFieldFLOAT32Value(14, maxSpeed, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns avg_heart_rate field
      // Units: bpm
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT8 GetAvgHeartRate(void) const
      {
         return GetFieldUINT8Value(15, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set avg_heart_rate field
      // Units: bpm
      ///////////////////////////////////////////////////////////////////////
      void SetAvgHeartRate(FIT_UINT8 avgHeartRate)
      {
         SetFieldUINT8Value(15, avgHeartRate, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns max_heart_rate field
      // Units: bpm
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT8 GetMaxHeartRate(void) const
      {
         return GetFieldUINT8Value(16, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set max_heart_rate field
      // Units: bpm
      ///////////////////////////////////////////////////////////////////////
      void SetMaxHeartRate(FIT_UINT8 maxHeartRate)
      {
         SetFieldUINT8Value(16, maxHeartRate, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns avg_cadence field
      // Units: rpm
      // Comment: total_cycles / total_timer_time if non_zero_avg_cadence otherwise total_cycles / total_elapsed_time
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT8 GetAvgCadence(void) const
      {
         return GetFieldUINT8Value(17, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set avg_cadence field
      // Units: rpm
      // Comment: total_cycles / total_timer_time if non_zero_avg_cadence otherwise total_cycles / total_elapsed_time
      ///////////////////////////////////////////////////////////////////////
      void SetAvgCadence(FIT_UINT8 avgCadence)
      {
         SetFieldUINT8Value(17, avgCadence, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns max_cadence field
      // Units: rpm
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT8 GetMaxCadence(void) const
      {
         return GetFieldUINT8Value(18, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set max_cadence field
      // Units: rpm
      ///////////////////////////////////////////////////////////////////////
      void SetMaxCadence(FIT_UINT8 maxCadence)
      {
         SetFieldUINT8Value(18, maxCadence, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns avg_power field
      // Units: watts
      // Comment: total_power / total_timer_time if non_zero_avg_power otherwise total_power / total_elapsed_time
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT16 GetAvgPower(void) const
      {
         return GetFieldUINT16Value(19, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set avg_power field
      // Units: watts
      // Comment: total_power / total_timer_time if non_zero_avg_power otherwise total_power / total_elapsed_time
      ///////////////////////////////////////////////////////////////////////
      void SetAvgPower(FIT_UINT16 avgPower)
      {
         SetFieldUINT16Value(19, avgPower, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns max_power field
      // Units: watts
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT16 GetMaxPower(void) const
      {
         return GetFieldUINT16Value(20, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set max_power field
      // Units: watts
      ///////////////////////////////////////////////////////////////////////
      void SetMaxPower(FIT_UINT16 maxPower)
      {
         SetFieldUINT16Value(20, maxPower, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns total_ascent field
      // Units: m
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT16 GetTotalAscent(void) const
      {
         return GetFieldUINT16Value(21, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set total_ascent field
      // Units: m
      ///////////////////////////////////////////////////////////////////////
      void SetTotalAscent(FIT_UINT16 totalAscent)
      {
         SetFieldUINT16Value(21, totalAscent, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns total_descent field
      // Units: m
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT16 GetTotalDescent(void) const
      {
         return GetFieldUINT16Value(22, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set total_descent field
      // Units: m
      ///////////////////////////////////////////////////////////////////////
      void SetTotalDescent(FIT_UINT16 totalDescent)
      {
         SetFieldUINT16Value(22, totalDescent, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns sport field
      ///////////////////////////////////////////////////////////////////////
      FIT_SPORT GetSport(void) const
      {
         return GetFieldENUMValue(23, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set sport field
      ///////////////////////////////////////////////////////////////////////
      void SetSport(FIT_SPORT sport)
      {
         SetFieldENUMValue(23, sport, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns event_group field
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT8 GetEventGroup(void) const
      {
         return GetFieldUINT8Value(24, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set event_group field
      ///////////////////////////////////////////////////////////////////////
      void SetEventGroup(FIT_UINT8 eventGroup)
      {
         SetFieldUINT8Value(24, eventGroup, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns nec_lat field
      // Units: semicircles
      // Comment: North east corner latitude.
      ///////////////////////////////////////////////////////////////////////
      FIT_SINT32 GetNecLat(void) const
      {
         return GetFieldSINT32Value(25, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set nec_lat field
      // Units: semicircles
      // Comment: North east corner latitude.
      ///////////////////////////////////////////////////////////////////////
      void SetNecLat(FIT_SINT32 necLat)
      {
         SetFieldSINT32Value(25, necLat, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns nec_long field
      // Units: semicircles
      // Comment: North east corner longitude.
      ///////////////////////////////////////////////////////////////////////
      FIT_SINT32 GetNecLong(void) const
      {
         return GetFieldSINT32Value(26, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set nec_long field
      // Units: semicircles
      // Comment: North east corner longitude.
      ///////////////////////////////////////////////////////////////////////
      void SetNecLong(FIT_SINT32 necLong)
      {
         SetFieldSINT32Value(26, necLong, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns swc_lat field
      // Units: semicircles
      // Comment: South west corner latitude.
      ///////////////////////////////////////////////////////////////////////
      FIT_SINT32 GetSwcLat(void) const
      {
         return GetFieldSINT32Value(27, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set swc_lat field
      // Units: semicircles
      // Comment: South west corner latitude.
      ///////////////////////////////////////////////////////////////////////
      void SetSwcLat(FIT_SINT32 swcLat)
      {
         SetFieldSINT32Value(27, swcLat, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns swc_long field
      // Units: semicircles
      // Comment: South west corner latitude.
      ///////////////////////////////////////////////////////////////////////
      FIT_SINT32 GetSwcLong(void) const
      {
         return GetFieldSINT32Value(28, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set swc_long field
      // Units: semicircles
      // Comment: South west corner latitude.
      ///////////////////////////////////////////////////////////////////////
      void SetSwcLong(FIT_SINT32 swcLong)
      {
         SetFieldSINT32Value(28, swcLong, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns name field
      ///////////////////////////////////////////////////////////////////////
      FIT_WSTRING GetName(void) const
      {
         return GetFieldSTRINGValue(29, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set name field
      ///////////////////////////////////////////////////////////////////////
      void SetName(FIT_WSTRING name)
      {
         SetFieldSTRINGValue(29, name, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns normalized_power field
      // Units: watts
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT16 GetNormalizedPower(void) const
      {
         return GetFieldUINT16Value(30, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set normalized_power field
      // Units: watts
      ///////////////////////////////////////////////////////////////////////
      void SetNormalizedPower(FIT_UINT16 normalizedPower)
      {
         SetFieldUINT16Value(30, normalizedPower, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns left_right_balance field
      ///////////////////////////////////////////////////////////////////////
      FIT_LEFT_RIGHT_BALANCE_100 GetLeftRightBalance(void) const
      {
         return GetFieldUINT16Value(31, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set left_right_balance field
      ///////////////////////////////////////////////////////////////////////
      void SetLeftRightBalance(FIT_LEFT_RIGHT_BALANCE_100 leftRightBalance)
      {
         SetFieldUINT16Value(31, leftRightBalance, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns sub_sport field
      ///////////////////////////////////////////////////////////////////////
      FIT_SUB_SPORT GetSubSport(void) const
      {
         return GetFieldENUMValue(32, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set sub_sport field
      ///////////////////////////////////////////////////////////////////////
      void SetSubSport(FIT_SUB_SPORT subSport)
      {
         SetFieldENUMValue(32, subSport, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns total_work field
      // Units: J
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT32 GetTotalWork(void) const
      {
         return GetFieldUINT32Value(33, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set total_work field
      // Units: J
      ///////////////////////////////////////////////////////////////////////
      void SetTotalWork(FIT_UINT32 totalWork)
      {
         SetFieldUINT32Value(33, totalWork, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns avg_altitude field
      // Units: m
      ///////////////////////////////////////////////////////////////////////
      FIT_FLOAT32 GetAvgAltitude(void) const
      {
         return GetFieldFLOAT32Value(34, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set avg_altitude field
      // Units: m
      ///////////////////////////////////////////////////////////////////////
      void SetAvgAltitude(FIT_FLOAT32 avgAltitude)
      {
         SetFieldFLOAT32Value(34, avgAltitude, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns max_altitude field
      // Units: m
      ///////////////////////////////////////////////////////////////////////
      FIT_FLOAT32 GetMaxAltitude(void) const
      {
         return GetFieldFLOAT32Value(35, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set max_altitude field
      // Units: m
      ///////////////////////////////////////////////////////////////////////
      void SetMaxAltitude(FIT_FLOAT32 maxAltitude)
      {
         SetFieldFLOAT32Value(35, maxAltitude, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns gps_accuracy field
      // Units: m
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT8 GetGpsAccuracy(void) const
      {
         return GetFieldUINT8Value(36, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set gps_accuracy field
      // Units: m
      ///////////////////////////////////////////////////////////////////////
      void SetGpsAccuracy(FIT_UINT8 gpsAccuracy)
      {
         SetFieldUINT8Value(36, gpsAccuracy, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns avg_grade field
      // Units: %
      ///////////////////////////////////////////////////////////////////////
      FIT_FLOAT32 GetAvgGrade(void) const
      {
         return GetFieldFLOAT32Value(37, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set avg_grade field
      // Units: %
      ///////////////////////////////////////////////////////////////////////
      void SetAvgGrade(FIT_FLOAT32 avgGrade)
      {
         SetFieldFLOAT32Value(37, avgGrade, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns avg_pos_grade field
      // Units: %
      ///////////////////////////////////////////////////////////////////////
      FIT_FLOAT32 GetAvgPosGrade(void) const
      {
         return GetFieldFLOAT32Value(38, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set avg_pos_grade field
      // Units: %
      ///////////////////////////////////////////////////////////////////////
      void SetAvgPosGrade(FIT_FLOAT32 avgPosGrade)
      {
         SetFieldFLOAT32Value(38, avgPosGrade, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns avg_neg_grade field
      // Units: %
      ///////////////////////////////////////////////////////////////////////
      FIT_FLOAT32 GetAvgNegGrade(void) const
      {
         return GetFieldFLOAT32Value(39, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set avg_neg_grade field
      // Units: %
      ///////////////////////////////////////////////////////////////////////
      void SetAvgNegGrade(FIT_FLOAT32 avgNegGrade)
      {
         SetFieldFLOAT32Value(39, avgNegGrade, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns max_pos_grade field
      // Units: %
      ///////////////////////////////////////////////////////////////////////
      FIT_FLOAT32 GetMaxPosGrade(void) const
      {
         return GetFieldFLOAT32Value(40, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set max_pos_grade field
      // Units: %
      ///////////////////////////////////////////////////////////////////////
      void SetMaxPosGrade(FIT_FLOAT32 maxPosGrade)
      {
         SetFieldFLOAT32Value(40, maxPosGrade, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns max_neg_grade field
      // Units: %
      ///////////////////////////////////////////////////////////////////////
      FIT_FLOAT32 GetMaxNegGrade(void) const
      {
         return GetFieldFLOAT32Value(41, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set max_neg_grade field
      // Units: %
      ///////////////////////////////////////////////////////////////////////
      void SetMaxNegGrade(FIT_FLOAT32 maxNegGrade)
      {
         SetFieldFLOAT32Value(41, maxNegGrade, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns avg_temperature field
      // Units: C
      ///////////////////////////////////////////////////////////////////////
      FIT_SINT8 GetAvgTemperature(void) const
      {
         return GetFieldSINT8Value(42, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set avg_temperature field
      // Units: C
      ///////////////////////////////////////////////////////////////////////
      void SetAvgTemperature(FIT_SINT8 avgTemperature)
      {
         SetFieldSINT8Value(42, avgTemperature, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns max_temperature field
      // Units: C
      ///////////////////////////////////////////////////////////////////////
      FIT_SINT8 GetMaxTemperature(void) const
      {
         return GetFieldSINT8Value(43, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set max_temperature field
      // Units: C
      ///////////////////////////////////////////////////////////////////////
      void SetMaxTemperature(FIT_SINT8 maxTemperature)
      {
         SetFieldSINT8Value(43, maxTemperature, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns total_moving_time field
      // Units: s
      ///////////////////////////////////////////////////////////////////////
      FIT_FLOAT32 GetTotalMovingTime(void) const
      {
         return GetFieldFLOAT32Value(44, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set total_moving_time field
      // Units: s
      ///////////////////////////////////////////////////////////////////////
      void SetTotalMovingTime(FIT_FLOAT32 totalMovingTime)
      {
         SetFieldFLOAT32Value(44, totalMovingTime, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns avg_pos_vertical_speed field
      // Units: m/s
      ///////////////////////////////////////////////////////////////////////
      FIT_FLOAT32 GetAvgPosVerticalSpeed(void) const
      {
         return GetFieldFLOAT32Value(45, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set avg_pos_vertical_speed field
      // Units: m/s
      ///////////////////////////////////////////////////////////////////////
      void SetAvgPosVerticalSpeed(FIT_FLOAT32 avgPosVerticalSpeed)
      {
         SetFieldFLOAT32Value(45, avgPosVerticalSpeed, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns avg_neg_vertical_speed field
      // Units: m/s
      ///////////////////////////////////////////////////////////////////////
      FIT_FLOAT32 GetAvgNegVerticalSpeed(void) const
      {
         return GetFieldFLOAT32Value(46, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set avg_neg_vertical_speed field
      // Units: m/s
      ///////////////////////////////////////////////////////////////////////
      void SetAvgNegVerticalSpeed(FIT_FLOAT32 avgNegVerticalSpeed)
      {
         SetFieldFLOAT32Value(46, avgNegVerticalSpeed, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns max_pos_vertical_speed field
      // Units: m/s
      ///////////////////////////////////////////////////////////////////////
      FIT_FLOAT32 GetMaxPosVerticalSpeed(void) const
      {
         return GetFieldFLOAT32Value(47, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set max_pos_vertical_speed field
      // Units: m/s
      ///////////////////////////////////////////////////////////////////////
      void SetMaxPosVerticalSpeed(FIT_FLOAT32 maxPosVerticalSpeed)
      {
         SetFieldFLOAT32Value(47, maxPosVerticalSpeed, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns max_neg_vertical_speed field
      // Units: m/s
      ///////////////////////////////////////////////////////////////////////
      FIT_FLOAT32 GetMaxNegVerticalSpeed(void) const
      {
         return GetFieldFLOAT32Value(48, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set max_neg_vertical_speed field
      // Units: m/s
      ///////////////////////////////////////////////////////////////////////
      void SetMaxNegVerticalSpeed(FIT_FLOAT32 maxNegVerticalSpeed)
      {
         SetFieldFLOAT32Value(48, maxNegVerticalSpeed, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns number of time_in_hr_zone
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT8 GetNumTimeInHrZone(void) const
      {
         return GetFieldNumValues(49, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns time_in_hr_zone field
      // Units: s
      ///////////////////////////////////////////////////////////////////////
      FIT_FLOAT32 GetTimeInHrZone(FIT_UINT8 index) const
      {
         return GetFieldFLOAT32Value(49, index, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set time_in_hr_zone field
      // Units: s
      ///////////////////////////////////////////////////////////////////////
      void SetTimeInHrZone(FIT_UINT8 index, FIT_FLOAT32 timeInHrZone)
      {
         SetFieldFLOAT32Value(49, timeInHrZone, index, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns number of time_in_speed_zone
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT8 GetNumTimeInSpeedZone(void) const
      {
         return GetFieldNumValues(50, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns time_in_speed_zone field
      // Units: s
      ///////////////////////////////////////////////////////////////////////
      FIT_FLOAT32 GetTimeInSpeedZone(FIT_UINT8 index) const
      {
         return GetFieldFLOAT32Value(50, index, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set time_in_speed_zone field
      // Units: s
      ///////////////////////////////////////////////////////////////////////
      void SetTimeInSpeedZone(FIT_UINT8 index, FIT_FLOAT32 timeInSpeedZone)
      {
         SetFieldFLOAT32Value(50, timeInSpeedZone, index, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns number of time_in_cadence_zone
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT8 GetNumTimeInCadenceZone(void) const
      {
         return GetFieldNumValues(51, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns time_in_cadence_zone field
      // Units: s
      ///////////////////////////////////////////////////////////////////////
      FIT_FLOAT32 GetTimeInCadenceZone(FIT_UINT8 index) const
      {
         return GetFieldFLOAT32Value(51, index, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set time_in_cadence_zone field
      // Units: s
      ///////////////////////////////////////////////////////////////////////
      void SetTimeInCadenceZone(FIT_UINT8 index, FIT_FLOAT32 timeInCadenceZone)
      {
         SetFieldFLOAT32Value(51, timeInCadenceZone, index, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns number of time_in_power_zone
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT8 GetNumTimeInPowerZone(void) const
      {
         return GetFieldNumValues(52, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns time_in_power_zone field
      // Units: s
      ///////////////////////////////////////////////////////////////////////
      FIT_FLOAT32 GetTimeInPowerZone(FIT_UINT8 index) const
      {
         return GetFieldFLOAT32Value(52, index, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set time_in_power_zone field
      // Units: s
      ///////////////////////////////////////////////////////////////////////
      void SetTimeInPowerZone(FIT_UINT8 index, FIT_FLOAT32 timeInPowerZone)
      {
         SetFieldFLOAT32Value(52, timeInPowerZone, index, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns repetition_num field
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT16 GetRepetitionNum(void) const
      {
         return GetFieldUINT16Value(53, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set repetition_num field
      ///////////////////////////////////////////////////////////////////////
      void SetRepetitionNum(FIT_UINT16 repetitionNum)
      {
         SetFieldUINT16Value(53, repetitionNum, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns min_altitude field
      // Units: m
      ///////////////////////////////////////////////////////////////////////
      FIT_FLOAT32 GetMinAltitude(void) const
      {
         return GetFieldFLOAT32Value(54, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set min_altitude field
      // Units: m
      ///////////////////////////////////////////////////////////////////////
      void SetMinAltitude(FIT_FLOAT32 minAltitude)
      {
         SetFieldFLOAT32Value(54, minAltitude, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns min_heart_rate field
      // Units: bpm
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT8 GetMinHeartRate(void) const
      {
         return GetFieldUINT8Value(55, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set min_heart_rate field
      // Units: bpm
      ///////////////////////////////////////////////////////////////////////
      void SetMinHeartRate(FIT_UINT8 minHeartRate)
      {
         SetFieldUINT8Value(55, minHeartRate, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns active_time field
      // Units: s
      ///////////////////////////////////////////////////////////////////////
      FIT_FLOAT32 GetActiveTime(void) const
      {
         return GetFieldFLOAT32Value(56, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set active_time field
      // Units: s
      ///////////////////////////////////////////////////////////////////////
      void SetActiveTime(FIT_FLOAT32 activeTime)
      {
         SetFieldFLOAT32Value(56, activeTime, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns wkt_step_index field
      ///////////////////////////////////////////////////////////////////////
      FIT_MESSAGE_INDEX GetWktStepIndex(void) const
      {
         return GetFieldUINT16Value(57, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set wkt_step_index field
      ///////////////////////////////////////////////////////////////////////
      void SetWktStepIndex(FIT_MESSAGE_INDEX wktStepIndex)
      {
         SetFieldUINT16Value(57, wktStepIndex, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns sport_event field
      ///////////////////////////////////////////////////////////////////////
      FIT_SPORT_EVENT GetSportEvent(void) const
      {
         return GetFieldENUMValue(58, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set sport_event field
      ///////////////////////////////////////////////////////////////////////
      void SetSportEvent(FIT_SPORT_EVENT sportEvent)
      {
         SetFieldENUMValue(58, sportEvent, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns avg_left_torque_effectiveness field
      // Units: percent
      ///////////////////////////////////////////////////////////////////////
      FIT_FLOAT32 GetAvgLeftTorqueEffectiveness(void) const
      {
         return GetFieldFLOAT32Value(59, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set avg_left_torque_effectiveness field
      // Units: percent
      ///////////////////////////////////////////////////////////////////////
      void SetAvgLeftTorqueEffectiveness(FIT_FLOAT32 avgLeftTorqueEffectiveness)
      {
         SetFieldFLOAT32Value(59, avgLeftTorqueEffectiveness, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns avg_right_torque_effectiveness field
      // Units: percent
      ///////////////////////////////////////////////////////////////////////
      FIT_FLOAT32 GetAvgRightTorqueEffectiveness(void) const
      {
         return GetFieldFLOAT32Value(60, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set avg_right_torque_effectiveness field
      // Units: percent
      ///////////////////////////////////////////////////////////////////////
      void SetAvgRightTorqueEffectiveness(FIT_FLOAT32 avgRightTorqueEffectiveness)
      {
         SetFieldFLOAT32Value(60, avgRightTorqueEffectiveness, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns avg_left_pedal_smoothness field
      // Units: percent
      ///////////////////////////////////////////////////////////////////////
      FIT_FLOAT32 GetAvgLeftPedalSmoothness(void) const
      {
         return GetFieldFLOAT32Value(61, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set avg_left_pedal_smoothness field
      // Units: percent
      ///////////////////////////////////////////////////////////////////////
      void SetAvgLeftPedalSmoothness(FIT_FLOAT32 avgLeftPedalSmoothness)
      {
         SetFieldFLOAT32Value(61, avgLeftPedalSmoothness, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns avg_right_pedal_smoothness field
      // Units: percent
      ///////////////////////////////////////////////////////////////////////
      FIT_FLOAT32 GetAvgRightPedalSmoothness(void) const
      {
         return GetFieldFLOAT32Value(62, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set avg_right_pedal_smoothness field
      // Units: percent
      ///////////////////////////////////////////////////////////////////////
      void SetAvgRightPedalSmoothness(FIT_FLOAT32 avgRightPedalSmoothness)
      {
         SetFieldFLOAT32Value(62, avgRightPedalSmoothness, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns avg_combined_pedal_smoothness field
      // Units: percent
      ///////////////////////////////////////////////////////////////////////
      FIT_FLOAT32 GetAvgCombinedPedalSmoothness(void) const
      {
         return GetFieldFLOAT32Value(63, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set avg_combined_pedal_smoothness field
      // Units: percent
      ///////////////////////////////////////////////////////////////////////
      void SetAvgCombinedPedalSmoothness(FIT_FLOAT32 avgCombinedPedalSmoothness)
      {
         SetFieldFLOAT32Value(63, avgCombinedPedalSmoothness, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns status field
      ///////////////////////////////////////////////////////////////////////
      FIT_SEGMENT_LAP_STATUS GetStatus(void) const
      {
         return GetFieldENUMValue(64, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set status field
      ///////////////////////////////////////////////////////////////////////
      void SetStatus(FIT_SEGMENT_LAP_STATUS status)
      {
         SetFieldENUMValue(64, status, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns uuid field
      ///////////////////////////////////////////////////////////////////////
      FIT_WSTRING GetUuid(void) const
      {
         return GetFieldSTRINGValue(65, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set uuid field
      ///////////////////////////////////////////////////////////////////////
      void SetUuid(FIT_WSTRING uuid)
      {
         SetFieldSTRINGValue(65, uuid, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns avg_fractional_cadence field
      // Units: rpm
      // Comment: fractional part of the avg_cadence
      ///////////////////////////////////////////////////////////////////////
      FIT_FLOAT32 GetAvgFractionalCadence(void) const
      {
         return GetFieldFLOAT32Value(66, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set avg_fractional_cadence field
      // Units: rpm
      // Comment: fractional part of the avg_cadence
      ///////////////////////////////////////////////////////////////////////
      void SetAvgFractionalCadence(FIT_FLOAT32 avgFractionalCadence)
      {
         SetFieldFLOAT32Value(66, avgFractionalCadence, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns max_fractional_cadence field
      // Units: rpm
      // Comment: fractional part of the max_cadence
      ///////////////////////////////////////////////////////////////////////
      FIT_FLOAT32 GetMaxFractionalCadence(void) const
      {
         return GetFieldFLOAT32Value(67, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set max_fractional_cadence field
      // Units: rpm
      // Comment: fractional part of the max_cadence
      ///////////////////////////////////////////////////////////////////////
      void SetMaxFractionalCadence(FIT_FLOAT32 maxFractionalCadence)
      {
         SetFieldFLOAT32Value(67, maxFractionalCadence, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns total_fractional_cycles field
      // Units: cycles
      // Comment: fractional part of the total_cycles
      ///////////////////////////////////////////////////////////////////////
      FIT_FLOAT32 GetTotalFractionalCycles(void) const
      {
         return GetFieldFLOAT32Value(68, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set total_fractional_cycles field
      // Units: cycles
      // Comment: fractional part of the total_cycles
      ///////////////////////////////////////////////////////////////////////
      void SetTotalFractionalCycles(FIT_FLOAT32 totalFractionalCycles)
      {
         SetFieldFLOAT32Value(68, totalFractionalCycles, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns front_gear_shift_count field
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT16 GetFrontGearShiftCount(void) const
      {
         return GetFieldUINT16Value(69, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set front_gear_shift_count field
      ///////////////////////////////////////////////////////////////////////
      void SetFrontGearShiftCount(FIT_UINT16 frontGearShiftCount)
      {
         SetFieldUINT16Value(69, frontGearShiftCount, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns rear_gear_shift_count field
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT16 GetRearGearShiftCount(void) const
      {
         return GetFieldUINT16Value(70, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set rear_gear_shift_count field
      ///////////////////////////////////////////////////////////////////////
      void SetRearGearShiftCount(FIT_UINT16 rearGearShiftCount)
      {
         SetFieldUINT16Value(70, rearGearShiftCount, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns time_standing field
      // Units: s
      // Comment: Total time spent in the standing position
      ///////////////////////////////////////////////////////////////////////
      FIT_FLOAT32 GetTimeStanding(void) const
      {
         return GetFieldFLOAT32Value(71, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set time_standing field
      // Units: s
      // Comment: Total time spent in the standing position
      ///////////////////////////////////////////////////////////////////////
      void SetTimeStanding(FIT_FLOAT32 timeStanding)
      {
         SetFieldFLOAT32Value(71, timeStanding, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns stand_count field
      // Comment: Number of transitions to the standing state
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT16 GetStandCount(void) const
      {
         return GetFieldUINT16Value(72, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set stand_count field
      // Comment: Number of transitions to the standing state
      ///////////////////////////////////////////////////////////////////////
      void SetStandCount(FIT_UINT16 standCount)
      {
         SetFieldUINT16Value(72, standCount, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns avg_left_pco field
      // Units: mm
      // Comment: Average left platform center offset
      ///////////////////////////////////////////////////////////////////////
      FIT_SINT8 GetAvgLeftPco(void) const
      {
         return GetFieldSINT8Value(73, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set avg_left_pco field
      // Units: mm
      // Comment: Average left platform center offset
      ///////////////////////////////////////////////////////////////////////
      void SetAvgLeftPco(FIT_SINT8 avgLeftPco)
      {
         SetFieldSINT8Value(73, avgLeftPco, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns avg_right_pco field
      // Units: mm
      // Comment: Average right platform center offset
      ///////////////////////////////////////////////////////////////////////
      FIT_SINT8 GetAvgRightPco(void) const
      {
         return GetFieldSINT8Value(74, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set avg_right_pco field
      // Units: mm
      // Comment: Average right platform center offset
      ///////////////////////////////////////////////////////////////////////
      void SetAvgRightPco(FIT_SINT8 avgRightPco)
      {
         SetFieldSINT8Value(74, avgRightPco, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns number of avg_left_power_phase
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT8 GetNumAvgLeftPowerPhase(void) const
      {
         return GetFieldNumValues(75, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns avg_left_power_phase field
      // Units: degrees
      // Comment: Average left power phase angles. Data value indexes defined by power_phase_type.
      ///////////////////////////////////////////////////////////////////////
      FIT_FLOAT32 GetAvgLeftPowerPhase(FIT_UINT8 index) const
      {
         return GetFieldFLOAT32Value(75, index, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set avg_left_power_phase field
      // Units: degrees
      // Comment: Average left power phase angles. Data value indexes defined by power_phase_type.
      ///////////////////////////////////////////////////////////////////////
      void SetAvgLeftPowerPhase(FIT_UINT8 index, FIT_FLOAT32 avgLeftPowerPhase)
      {
         SetFieldFLOAT32Value(75, avgLeftPowerPhase, index, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns number of avg_left_power_phase_peak
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT8 GetNumAvgLeftPowerPhasePeak(void) const
      {
         return GetFieldNumValues(76, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns avg_left_power_phase_peak field
      // Units: degrees
      // Comment: Average left power phase peak angles. Data value indexes defined by power_phase_type.
      ///////////////////////////////////////////////////////////////////////
      FIT_FLOAT32 GetAvgLeftPowerPhasePeak(FIT_UINT8 index) const
      {
         return GetFieldFLOAT32Value(76, index, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set avg_left_power_phase_peak field
      // Units: degrees
      // Comment: Average left power phase peak angles. Data value indexes defined by power_phase_type.
      ///////////////////////////////////////////////////////////////////////
      void SetAvgLeftPowerPhasePeak(FIT_UINT8 index, FIT_FLOAT32 avgLeftPowerPhasePeak)
      {
         SetFieldFLOAT32Value(76, avgLeftPowerPhasePeak, index, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns number of avg_right_power_phase
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT8 GetNumAvgRightPowerPhase(void) const
      {
         return GetFieldNumValues(77, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns avg_right_power_phase field
      // Units: degrees
      // Comment: Average right power phase angles. Data value indexes defined by power_phase_type.
      ///////////////////////////////////////////////////////////////////////
      FIT_FLOAT32 GetAvgRightPowerPhase(FIT_UINT8 index) const
      {
         return GetFieldFLOAT32Value(77, index, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set avg_right_power_phase field
      // Units: degrees
      // Comment: Average right power phase angles. Data value indexes defined by power_phase_type.
      ///////////////////////////////////////////////////////////////////////
      void SetAvgRightPowerPhase(FIT_UINT8 index, FIT_FLOAT32 avgRightPowerPhase)
      {
         SetFieldFLOAT32Value(77, avgRightPowerPhase, index, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns number of avg_right_power_phase_peak
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT8 GetNumAvgRightPowerPhasePeak(void) const
      {
         return GetFieldNumValues(78, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns avg_right_power_phase_peak field
      // Units: degrees
      // Comment: Average right power phase peak angles. Data value indexes defined by power_phase_type.
      ///////////////////////////////////////////////////////////////////////
      FIT_FLOAT32 GetAvgRightPowerPhasePeak(FIT_UINT8 index) const
      {
         return GetFieldFLOAT32Value(78, index, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set avg_right_power_phase_peak field
      // Units: degrees
      // Comment: Average right power phase peak angles. Data value indexes defined by power_phase_type.
      ///////////////////////////////////////////////////////////////////////
      void SetAvgRightPowerPhasePeak(FIT_UINT8 index, FIT_FLOAT32 avgRightPowerPhasePeak)
      {
         SetFieldFLOAT32Value(78, avgRightPowerPhasePeak, index, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns number of avg_power_position
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT8 GetNumAvgPowerPosition(void) const
      {
         return GetFieldNumValues(79, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns avg_power_position field
      // Units: watts
      // Comment: Average power by position. Data value indexes defined by rider_position_type.
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT16 GetAvgPowerPosition(FIT_UINT8 index) const
      {
         return GetFieldUINT16Value(79, index, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set avg_power_position field
      // Units: watts
      // Comment: Average power by position. Data value indexes defined by rider_position_type.
      ///////////////////////////////////////////////////////////////////////
      void SetAvgPowerPosition(FIT_UINT8 index, FIT_UINT16 avgPowerPosition)
      {
         SetFieldUINT16Value(79, avgPowerPosition, index, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns number of max_power_position
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT8 GetNumMaxPowerPosition(void) const
      {
         return GetFieldNumValues(80, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns max_power_position field
      // Units: watts
      // Comment: Maximum power by position. Data value indexes defined by rider_position_type.
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT16 GetMaxPowerPosition(FIT_UINT8 index) const
      {
         return GetFieldUINT16Value(80, index, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set max_power_position field
      // Units: watts
      // Comment: Maximum power by position. Data value indexes defined by rider_position_type.
      ///////////////////////////////////////////////////////////////////////
      void SetMaxPowerPosition(FIT_UINT8 index, FIT_UINT16 maxPowerPosition)
      {
         SetFieldUINT16Value(80, maxPowerPosition, index, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns number of avg_cadence_position
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT8 GetNumAvgCadencePosition(void) const
      {
         return GetFieldNumValues(81, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns avg_cadence_position field
      // Units: rpm
      // Comment: Average cadence by position. Data value indexes defined by rider_position_type.
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT8 GetAvgCadencePosition(FIT_UINT8 index) const
      {
         return GetFieldUINT8Value(81, index, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set avg_cadence_position field
      // Units: rpm
      // Comment: Average cadence by position. Data value indexes defined by rider_position_type.
      ///////////////////////////////////////////////////////////////////////
      void SetAvgCadencePosition(FIT_UINT8 index, FIT_UINT8 avgCadencePosition)
      {
         SetFieldUINT8Value(81, avgCadencePosition, index, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns number of max_cadence_position
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT8 GetNumMaxCadencePosition(void) const
      {
         return GetFieldNumValues(82, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns max_cadence_position field
      // Units: rpm
      // Comment: Maximum cadence by position. Data value indexes defined by rider_position_type.
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT8 GetMaxCadencePosition(FIT_UINT8 index) const
      {
         return GetFieldUINT8Value(82, index, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set max_cadence_position field
      // Units: rpm
      // Comment: Maximum cadence by position. Data value indexes defined by rider_position_type.
      ///////////////////////////////////////////////////////////////////////
      void SetMaxCadencePosition(FIT_UINT8 index, FIT_UINT8 maxCadencePosition)
      {
         SetFieldUINT8Value(82, maxCadencePosition, index, FIT_SUBFIELD_INDEX_MAIN_FIELD);
      }

};

} // namespace fit

#endif // !defined(FIT_SEGMENT_LAP_MESG_HPP)
